const nameDrinkReturn = {
  drinks: [
    {
      idDrink: '11113',
      strDrink: 'Bloody Mary',
      strDrinkAlternate: null,
      strTags: 'IBA,ContemporaryClassic',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: 'Contemporary Classics',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Old-fashioned glass',
      strInstructions: 'Stirring gently, pour all ingredients into highball glass. Garnish.',
      strInstructionsES: null,
      strInstructionsDE: 'Unter leichtem Rühren alle Zutaten in ein Highball-Glas geben. Garnieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Mescolando delicatamente, versare tutti gli ingredienti nel bicchiere highball.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/t6caa21582485702.jpg',
      strIngredient1: 'Vodka',
      strIngredient2: 'Tomato juice',
      strIngredient3: 'Lemon juice',
      strIngredient4: 'Worcestershire sauce',
      strIngredient5: 'Tabasco sauce',
      strIngredient6: 'Lime',
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '3 oz ',
      strMeasure3: '1 dash ',
      strMeasure4: '1/2 tsp ',
      strMeasure5: '2-3 drops ',
      strMeasure6: '1 wedge ',
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://www.thecocktaildb.com/drink/11113-Bloody-Mary',
      strImageAttribution: 'TheCocktialDB.com',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2015-08-18 15:09:14',
    },
    {
      idDrink: '11112',
      strDrink: 'Bloody Maria',
      strDrinkAlternate: null,
      strTags: 'Breakfast,Brunch,Hangover',
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Old-fashioned glass',
      strInstructions: 'Shake all ingredients (except lemon slice) with cracked ice and strain into an old-fashioned glass over ice cubes. Add the slice of lemon and serve.',
      strInstructionsES: null,
      strInstructionsDE: 'Alle Zutaten (außer Zitronenscheibe) mit zerkleinertem Eis schütteln und über Eiswürfel in ein old-fashioned Glas seihen. Die Zitronenscheibe dazugeben und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare tutti gli ingredienti (eccetto la fetta di limone) con ghiaccio tritato e filtrare in un bicchiere vecchio stile su cubetti di ghiaccio.Aggiungere la fetta di limone e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yz0j6z1504389461.jpg',
      strIngredient1: 'Tequila',
      strIngredient2: 'Tomato juice',
      strIngredient3: 'Lemon juice',
      strIngredient4: 'Tabasco sauce',
      strIngredient5: 'Celery salt',
      strIngredient6: 'Lemon',
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '2 oz ',
      strMeasure3: '1 dash ',
      strMeasure4: '1 dash ',
      strMeasure5: '1 dash ',
      strMeasure6: '1 slice ',
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 22:57:41',
    },
    {
      idDrink: '178312',
      strDrink: 'Bloody Punch',
      strDrinkAlternate: null,
      strTags: 'Halloween',
      strVideo: null,
      strCategory: 'Punch / Party Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Punch bowl',
      strInstructions: 'Place the thawed strawberries in a large bowl. Mash them with a fork to ensure no large chunks.\r\n\r\nStep\r\n2\r\n\r\n \r\nIn a punch bowl or pitcher, combine mashed strawberries, lime pulp and soda. Mix well.\r\n\r\nStep\r\n3\r\n\r\n \r\nAdd blueberries and raisins. They will float and look like bugs in the punch.',
      strInstructionsES: null,
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT: 'Metti le fragole in una grande ciotola. Schiacciateli con un cucchiaio per assicurarvi che non ci siano grossi pezzi.\r\nPasso 2\r\nIn una ciotola da punch o in una brocca, unisci il purè di fragole, la polpa di lime e la soda. Mescolare bene.\r\nPassaggio 3\r\nAggiungere i mirtilli e l\'uvetta. Galleggeranno e sembreranno insetti nel pugno.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/5yhd3n1571687385.jpg',
      strIngredient1: 'Vodka',
      strIngredient2: 'Strawberries',
      strIngredient3: 'Lime Juice',
      strIngredient4: 'Lemon-lime soda',
      strIngredient5: 'Lemon-lime soda',
      strIngredient6: 'Raisins',
      strIngredient7: 'Blueberries',
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '10 shots',
      strMeasure2: '3 cups',
      strMeasure3: '1/2 cup',
      strMeasure4: '12 oz',
      strMeasure5: '12 oz',
      strMeasure6: '1 cup',
      strMeasure7: '1 cup',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: null,
    },
  ],
};

export default nameDrinkReturn;
