const VEGETABLE_OIL = 'Vegetable Oil';
const CHICKEN_STOCK = 'Chicken Stock';

const nameMealReturn = {
  meals: [
    {
      idMeal: '52965',
      strMeal: 'Breakfast Potatoes',
      strDrinkAlternate: null,
      strCategory: 'Breakfast',
      strArea: 'Canadian',
      strInstructions: 'Before you do anything, freeze your bacon slices that way when you\'re ready to prep, it\'ll be so much easier to chop!\r\nWash the potatoes and cut medium dice into square pieces. To prevent any browning, place the already cut potatoes in a bowl filled with water.\r\nIn the meantime, heat 1-2 tablespoons of oil in a large skillet over medium-high heat. Tilt the skillet so the oil spreads evenly.\r\nOnce the oil is hot, drain the potatoes and add to the skillet. Season with salt, pepper, and Old Bay as needed.\r\nCook for 10 minutes, stirring the potatoes often, until brown. If needed, add a tablespoon more of oil.\r\nChop up the bacon and add to the potatoes. The bacon will start to render and the fat will begin to further cook the potatoes. Toss it up a bit! The bacon will take 5-6 minutes to crisp.\r\nOnce the bacon is cooked, reduce the heat to medium-low, add the minced garlic and toss. Season once more. Add dried or fresh parsley. Control heat as needed.\r\nLet the garlic cook until fragrant, about one minute.\r\nJust before serving, drizzle over the maple syrup and toss. Let that cook another minute, giving the potatoes a caramelized effect.\r\nServe in a warm bowl with a sunny side up egg!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1550441882.jpg',
      strTags: 'Breakfast,Brunch,',
      strYoutube: 'https://www.youtube.com/watch?v=BoD0TIO9nE4',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Bacon',
      strIngredient4: 'Garlic Clove',
      strIngredient5: 'Maple Syrup',
      strIngredient6: 'Parsley',
      strIngredient7: 'Salt',
      strIngredient8: 'Pepper',
      strIngredient9: 'Allspice',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '3 Medium',
      strMeasure2: '1 tbs',
      strMeasure3: '2 strips',
      strMeasure4: 'Minced',
      strMeasure5: '1 tbs',
      strMeasure6: 'Garnish',
      strMeasure7: 'Pinch',
      strMeasure8: 'Pinch',
      strMeasure9: 'To taste',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://www.vodkaandbiscuits.com/2014/03/06/bangin-breakfast-potatoes/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52877',
      strMeal: 'Lamb and Potato pie',
      strDrinkAlternate: null,
      strCategory: 'Lamb',
      strArea: 'British',
      strInstructions: 'Dust the meat with flour to lightly coat.\r\nHeat enough vegetable oil in a large saucepan to fill the base, and fry the onion and meat until lightly browned. Season with salt and pepper.\r\nAdd the carrots, stock and more seasoning to taste.\r\nBring to the boil, cover and reduce the heat to a simmer. Simmer for at least an hour or until the meat is tender. Take your time cooking the meat, the longer you leave it to cook, the better the flavour will be.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nAdd the drained potato cubes to the lamb.\r\nTurn the mixture into a pie dish or casserole and cover with the shortcrust pastry. Make three slits in the top of the pastry to release any steam while cooking.\r\nBrush with beaten egg and bake for about 40 minutes, until the pastry is golden brown.\r\nServe.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sxrpws1511555907.jpg',
      strTags: 'Pie',
      strYoutube: 'https://www.youtube.com/watch?v=NCyPaaUNYUk',
      strIngredient1: 'Lamb Shoulder',
      strIngredient2: 'Flour',
      strIngredient3: VEGETABLE_OIL,
      strIngredient4: 'Onion',
      strIngredient5: 'Carrots',
      strIngredient6: 'Vegetable Stock',
      strIngredient7: 'Potatoes',
      strIngredient8: 'Shortcrust Pastry',
      strIngredient9: 'Eggs',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '500g',
      strMeasure2: '1 tbls',
      strMeasure3: 'Dash',
      strMeasure4: '1 sliced',
      strMeasure5: '2 sliced',
      strMeasure6: '350ml/12fl',
      strMeasure7: '500g',
      strMeasure8: '450g',
      strMeasure9: 'To Glaze',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbc.co.uk/food/recipes/lambandpotatopie_83913',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52914',
      strMeal: 'Boulangère Potatoes',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'French',
      strInstructions: 'Heat oven to 200C/fan 180C/gas 6. Fry the onions and thyme sprigs in the oil until softened and lightly coloured (about 5 mins).\r\nSpread a layer of potatoes over the base of a 1.5-litre oiled gratin dish. Sprinkle over a few onions (see picture, above) and continue layering, finishing with a layer of potatoes. Pour over the stock and bake for 50-60 mins until the potatoes are cooked and the top is golden and crisp.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qywups1511796761.jpg',
      strTags: 'SideDish',
      strYoutube: 'https://www.youtube.com/watch?v=gcXPruv1Mjg',
      strIngredient1: 'Onions',
      strIngredient2: 'Thyme',
      strIngredient3: 'Olive Oil',
      strIngredient4: 'Potatoes',
      strIngredient5: 'Vegetable Stock',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 finely chopped',
      strMeasure2: 'sprigs of fresh',
      strMeasure3: '2 tbs',
      strMeasure4: '1.5kg',
      strMeasure5: '425g',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/5056/boulangre-potatoes',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52780',
      strMeal: 'Potato Gratin with Chicken',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Unknown',
      strInstructions: '15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn\'t have to take 45mins, it\'s nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It\'s always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft. Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock. Cook till the onions are soft then drain the potatoes and pour onto the onions. Season and spoon over cream or creme fraiche till all is covered but not swimming. Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=p3u8eiy3yHI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Onions',
      strIngredient3: 'Olive Oil',
      strIngredient4: CHICKEN_STOCK,
      strIngredient5: 'Creme Fraiche',
      strIngredient6: 'Parmesan',
      strIngredient7: 'Chicken Breasts',
      strIngredient8: 'Bacon',
      strIngredient9: 'Spinach',
      strIngredient10: 'Peas',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '800g',
      strMeasure2: '3',
      strMeasure3: '2 tblsp',
      strMeasure4: '100ml',
      strMeasure5: '1 pot',
      strMeasure6: 'Topping',
      strMeasure7: '4',
      strMeasure8: '4',
      strMeasure9: 'Topping',
      strMeasure10: 'Topping',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: 'https://www.instagram.com/p/BHxR7hYBJ6P',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52797',
      strMeal: 'Spicy North African Potato Salad',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Moroccan',
      strInstructions: 'Cook potatoes - place potatoes in a pot of cold water, and bring to the boil. Boil 20 minutes, or until potatoes are tender. You know they are cooked when you can stick a knife in them and the knife goes straight through.\r\nCombine harissa spice, olive oil, salt and pepper and lemon juice in a small bowl and whisk until combined.\r\nOnce potatoes are cooked, drain water and roughly chop potatoes in half.\r\nAdd harissa mix and spring onions/green onions to potatoes and stir.\r\nIn a large salad bowl, lay out arugula/rocket.\r\nTop with potato mix and toss.\r\nAdd fetta, mint and sprinkle over pine nuts.\r\nAdjust salt and pepper to taste.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urtwux1486983078.jpg',
      strTags: 'Vegetarian,Spicy',
      strYoutube: 'https://www.youtube.com/watch?v=zxBzwJvTK4g',
      strIngredient1: 'Small Potatoes',
      strIngredient2: 'Harissa Spice',
      strIngredient3: 'olive oil',
      strIngredient4: 'Lemon',
      strIngredient5: 'Spring onions',
      strIngredient6: 'Rocket',
      strIngredient7: 'Feta',
      strIngredient8: 'Mint',
      strIngredient9: 'Pine nuts',
      strIngredient10: 'Salt',
      strIngredient11: 'Pepper',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '650g/1lb 8 oz',
      strMeasure2: '1 tsp',
      strMeasure3: '2 tsp',
      strMeasure4: 'juice of half',
      strMeasure5: '4',
      strMeasure6: '150g/6oz',
      strMeasure7: '80g/3oz',
      strMeasure8: '20 chopped',
      strMeasure9: '2 tablespoons',
      strMeasure10: 'Pinch',
      strMeasure11: 'Pinch',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: '',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52993',
      strMeal: 'Honey Balsamic Chicken with Crispy Broccoli & Potatoes',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'American',
      strInstructions: '2 Servings\r\n\r\n1. Preheat oven to 425 degrees. Wash and dry all produce. Cut potatoes into 1/2-inch-thick wedges. Toss on one side of a baking sheet with a drizzle of oil, salt, and pepper. (For 4 servings, spread potatoes out across entire sheet.) Roast on top rack for 5 minutes (we\'ll add the broccoli then). \r\n\r\n2. Meanwhile, cut broccoli florets into bite-size pieces, if necessary. Peel and finely chop garlic. In a small microwave-safe bowl, combine 1 TBSP olive oil (2 TBSP for 4 servings) and half the garlic. Microwave until garlic sizzles, 30 seconds. \r\n\r\n3. Once potatoes have roasted 5 minutes, remove sheet from oven and add broccoli to empty side; carefully toss with garlic oil, salt, and pepper. (For 4 servings, add broccoli to a second sheet.) Continue roasting until potatoes and broccoli are browned and crispy, 15-20 minutes more. \r\n\r\n4. While veggies roast, pat chicken dry with paper towels; season all over with salt and pepper. Heat a drizzle of oil in a large pan over medium-high heat. Add chicken and cook until browned and cooked through, 5-6 minutes per side. (If chicken browns too quickly, reduce heat to medium.) Turn off heat; set chicken aside to rest. Wash out pan. \r\n\r\n5. Heat pan used for chicken over medium-high heat. Add a drizzle of oil and remaining garlic; cook until fragrant, 30 seconds. Stir in vinegar, honey, stock concentrate, and 1/4 cup water (1/3 cup for 4 servings). Simmer until thick and glossy, 2-3 minutes. Remove from heat and stir in 1 TBSP butter (2 TBSP for 4). Season with salt and pepper. \r\n\r\n6. Return chicken to pan and turn to coat in glaze. Divide chicken, broccoli, and potatoes between plates. Spoon any remaining glaze over chicken and serve. ',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/kvbotn1581012881.jpg',
      strTags: null,
      strYoutube: '',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Broccoli',
      strIngredient3: 'Garlic',
      strIngredient4: 'Chicken Breast',
      strIngredient5: 'Balsamic Vinegar',
      strIngredient6: 'Honey',
      strIngredient7: CHICKEN_STOCK,
      strIngredient8: 'Butter',
      strIngredient9: VEGETABLE_OIL,
      strIngredient10: 'Olive Oil',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '5',
      strMeasure2: '1',
      strMeasure3: '2 cloves',
      strMeasure4: '2',
      strMeasure5: ' ',
      strMeasure6: ' ',
      strMeasure7: ' ',
      strMeasure8: '1 tbsp',
      strMeasure9: '1 tbsp',
      strMeasure10: '1 tbsp',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: '',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52996',
      strMeal: 'French Onion Chicken with Roasted Carrots & Mashed Potatoes',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'American',
      strInstructions: '1\r\n\r\nPreheat oven to 425 degrees. Wash and dry all produce. Trim, peel, and cut carrots on a diagonal into ¼-inch-thick pieces. Dice potatoes into ½-inch pieces. Halve, peel, and thinly slice onion.\r\n\r\n2\r\n\r\nToss carrots on a baking sheet with a drizzle of oil, salt, and pepper. Roast until browned and tender, 15-20 minutes.\r\n\r\n3\r\n\r\nMeanwhile, place potatoes in a medium pot with enough salted water to cover by 2 inches. Bring to a boil and cook until tender, 12-15 minutes. Drain and return potatoes to pot; cover to keep warm.\r\n\r\n4\r\n\r\nWhile potatoes cook, heat a drizzle of oil in a large pan over medium-high heat. Add onion and cook, stirring occasionally, until lightly browned and softened, 8-10 minutes. Sprinkle with 1 tsp sugar (2 tsp for 4 servings). Stir in stock concentrate and 2 TBSP water (¼ cup for 4); season with salt and pepper. Cook until jammy, 2-3 minutes more. Turn off heat; transfer to a small bowl. Wash out pan.\r\n\r\n5\r\n\r\nPat chicken dry with paper towels; season all over with salt and pepper. Heat a drizzle of oil in pan used for onion over medium-high heat. Add chicken and cook until browned and cooked through, 5-6 minutes per side. In the last 1-2 minutes of cooking, top with caramelized onion and cheese. Cover pan until cheese melts. (If your pan doesn’t have a lid, cover with a baking sheet!)\r\n\r\n6\r\n\r\nHeat pot with drained potatoes over low heat; mash with sour cream, 2 TBSP butter (4 TBSP for 4 servings), salt, pepper, and a splash of water (or milk, for extra richness) until smooth. Divide chicken, roasted carrots, and mashed potatoes between plates.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/b5ft861583188991.jpg',
      strTags: null,
      strYoutube: '',
      strIngredient1: 'Chicken Breasts',
      strIngredient2: 'Carrots',
      strIngredient3: 'Small Potatoes',
      strIngredient4: 'Onion',
      strIngredient5: 'Beef Stock',
      strIngredient6: 'Mozzarella',
      strIngredient7: 'Sour Cream',
      strIngredient8: 'Butter',
      strIngredient9: 'Sugar',
      strIngredient10: VEGETABLE_OIL,
      strIngredient11: 'Salt',
      strIngredient12: 'Pepper',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2',
      strMeasure2: '12 ounces',
      strMeasure3: '5',
      strMeasure4: '1',
      strMeasure5: '1',
      strMeasure6: '1 1/2 cup ',
      strMeasure7: '2 tbsp',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: '',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52994',
      strMeal: 'Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini',
      strDrinkAlternate: null,
      strCategory: 'Pork',
      strArea: 'American',
      strInstructions: '\r\nServes 2\r\n\r\n\r\n1. \r\n\r\nAdjust racks to top and middle positions and preheat oven to 450 degrees. Wash and dry all produce. Dice sweet potatoes into 1/2-inch pieces. Toss on a baking sheet with a drizzle of oil, salt, and pepper. Roast on top rack for 12 minutes (we\'ll roast the zucchini then). \r\n\r\n\r\n2. \r\n\r\nMeanwhile, halve and core apple; thinly slice into half-moons. Peel and finely chop garlic. Quarter lemon. Trim and halve zucchini lengthwise; cut crosswise into 1/2-inch-thick half-moons. Toss on a second baking sheet with a drizzle of oil and a pinch of salt and pepper. Set aside. \r\n\r\n\r\n3. \r\n\r\nPat pork dry with paper towels and season all over with salt and pepper. Heat a drizzle of oil in a large pan over medium-high heat. Add pork and cook until browned and cooked through, 4-5 minutes per side. Turn off heat; transfer to a plate. \r\n\r\n\r\n4. \r\n\r\nOnce sweet potatoes have roasted 12 minutes, transfer baking sheet with zucchini to middle rack and continue roasting until both veggies are browned and softened, 12-15 minutes more. \r\n\r\n\r\n5. \r\n\r\nMeanwhile, melt 1 TBSP butter (2 TBSP for 4 servings) in pan used for pork over medium-high heat. Add apple and season with salt and pepper. Cook, scraping up any browned bits from bottom of pan, until apple is slightly softened, 2-3 minutes. Add garlic; cook until fragrant, 30 seconds. Add 1/z cup water (3/4 cup for 4), stock concentrate, and 11/2 tsp sugar (3 tsp for 4). Cook, stirring, until sauce has thickened and apple is very tender, 3-5 minutes. Season with salt and pepper. \r\n\r\n\r\n6. \r\n\r\nRemove pan with apple from heat; stir in 1 TBSP butter (2 TBSP for 4 servings) and a squeeze of lemon juice. Divide pork, zucchini, and sweet potatoes between plates. Top pork with glazed apple sauce. Top zucchini with a squeeze of lemon juice. ',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/h3ijwo1581013377.jpg',
      strTags: null,
      strYoutube: '',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Apples',
      strIngredient3: 'Garlic',
      strIngredient4: 'Lemon',
      strIngredient5: 'Pork',
      strIngredient6: 'Zucchini',
      strIngredient7: CHICKEN_STOCK,
      strIngredient8: VEGETABLE_OIL,
      strIngredient9: 'Sugar',
      strIngredient10: 'Butter',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2',
      strMeasure2: '1',
      strMeasure3: '2 cloves',
      strMeasure4: '1',
      strMeasure5: '2',
      strMeasure6: '1',
      strMeasure7: '1',
      strMeasure8: '1 tbsp',
      strMeasure9: '1 1/2 tsp ',
      strMeasure10: '2 tbsp',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: '',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52992',
      strMeal: 'Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'American',
      strInstructions: '1. Preheat oven to 425 degrees. Wash and dry all produce. Dice potatoes into 1/2-inch pieces. Trim, peel, and cut carrots on a diagonal into 1/2-inch-thick pieces. Trim and thinly slice scallions, separating whites from greens; finely chop whites. Peel and finely chop garlic.\r\n\r\n2. In a medium bowl, soak bread with 2 TBSP water (4 TBSP for 4 servings); break up with your hands until pasty. Stir in beef, sriracha, scallion whites, half the garlic, salt (we used 3/4 tsp kosher salt; 11/2 tsp for 4), and pepper. Form into two 1-inch-tall loaves (four loaves for 4). Place on one side of a baking sheet. Toss carrots on empty side of same sheet with a drizzle of oil, salt, and pepper. (For 4, spread meatloaves out across whole sheet and add carrots to a second sheet.) Bake for 20 minutes (we\'ll glaze the meatloaves then).\r\n\r\n3. Meanwhile, place potatoes in a medium pot with enough salted water to cover by 2 inches. Bring to a boil and cook until very\r\ntender, 12-15 minutes. Reserve 1/2 cup potato cooking liquid, then drain. While potatoes cook, in a small bowl, combine soy sauce, garlic powder, 1/4 cup ketchup (1/2 cup for 4 servings), and 2 tsp sugar (4 tsp for 4).\r\n\r\n4. Once meatloaves and carrots have baked 20 minutes, remove from oven. Spoon half the ketchup glaze over meatloaves (save\r\nthe rest for serving); return to oven until carrots are browned and tender, meatloaves are cooked through, and glaze is tacky, 4-5 minutes more.\r\n\r\n5. Meanwhile, melt 2 TBSP butter (4 TBSP for 4 servings) in pot used for potatoes over medium heat. Add remaining garlic and cook\r\nuntil fragrant, 30 seconds. Add potatoes and 1/4 tsp wasabi. Mash, adding splashes of reserved potato cooking liquid as necessary until smooth. Season with salt and pepper. (If you like things spicy, stir in more wasabi!)\r\n\r\n6. Divide meatloaves, mashed potatoes, and roasted carrots between plates. Sprinkle with scallion greens and serve with remaining ketchup glaze on the side for dipping.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/o2wb6p1581005243.jpg',
      strTags: null,
      strYoutube: '',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Carrots',
      strIngredient3: 'Scallions',
      strIngredient4: 'Garlic',
      strIngredient5: 'Bread',
      strIngredient6: 'Garlic Powder',
      strIngredient7: 'Soy Sauce',
      strIngredient8: 'Ground Beef',
      strIngredient9: VEGETABLE_OIL,
      strIngredient10: 'Sugar',
      strIngredient11: 'Butter',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '5',
      strMeasure2: '12 ounces',
      strMeasure3: '1',
      strMeasure4: '2 cloves',
      strMeasure5: '1 Slice',
      strMeasure6: '1',
      strMeasure7: '2',
      strMeasure8: '1',
      strMeasure9: '1 tsp ',
      strMeasure10: '2 tsp',
      strMeasure11: '2 tbsp',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: '',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export default nameMealReturn;
